### ISSUE TITLE
run-bmark-tests fails with TinyConfig?

### ISSUE THREAD

**Issue by jimmysitu** [chipsalliance/rocket-chip#1631] opened 2018-09-18 02:09 UTC
**Type of issue**: bug report

**Impact**:  unknown

**Development Phase**: proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
make run-bmark-tests CONFIG=TinyConfig

**What is the current behavior?**
  [ FAILED ] output/median.riscv.out 	 (tohost = 1337)
  [ FAILED ] output/median.riscv.out 	 via dtm (code = 1337, seed 1537207289) after 122660 cycles

**What is the expected behavior?**
I am not sure if TinyConfig is suppose to pass these bmark tests

**Please tell us about your environment:**
version: a3419df7
OS: Linux 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**What is the use case for changing the behavior?**
Is there any way to make sure TinyConfig works correctly?

**Comment by michael-etzkorn** [comment] 2022-03-26 22:47
Seems to be a duplicate of #430 -- RocketChip's TinyConfig will not work on tests that require more than 16kb of memory.

**Closed** 2022-04-12 22:27 UTC
